package app.pastehub.api.image;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
import org.springframework.beans.factory.annotation.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import app.pastehub.api.transfer.TransferService; import software.amazon.awssdk.services.s3.*; import software.amazon.awssdk.services.s3.model.*; import software.amazon.awssdk.services.s3.presigner.*; import software.amazon.awssdk.services.s3.presigner.model.*;
@Service public class ImageTransferService {
 static final Set<String> TYPES=Set.of("image/jpeg","image/png","image/webp"); static final char[] ALPH="ABCDEFGHJKMNPQRSTUVWXYZ23456789".toCharArray(); final ImageTransferRepository repo; final TransferService text; final S3Client s3; final S3Presigner presigner; final String bucket; final SecureRandom random=new SecureRandom();
 ImageTransferService(ImageTransferRepository repo,TransferService text,S3Client s3,S3Presigner p,@Value("${pastehub.s3.bucket}") String bucket){this.repo=repo;this.text=text;this.s3=s3;presigner=p;this.bucket=bucket;}
 @Transactional Init init(String mime,long size){if(!TYPES.contains(mime)||size<=0||size>10*1024*1024)throw new InvalidImageException(); try{s3.createBucket(CreateBucketRequest.builder().bucket(bucket).build());}catch(S3Exception ignored){} Instant now=Instant.now();String id=UUID.randomUUID().toString(),key="transfers/"+id+"/image",token=value(43);repo.save(new ImageTransfer(id,key,mime,size,hash(token),now));String url=presigner.presignPutObject(PutObjectPresignRequest.builder().signatureDuration(Duration.ofMinutes(5)).putObjectRequest(PutObjectRequest.builder().bucket(bucket).key(key).contentType(mime).contentLength(size).build()).build()).url().toString();return new Init(id,url,token);}
 @Transactional Created complete(String id,String token){ImageTransfer t=repo.findById(id).orElseThrow(ImageUnavailableException::new);if(!"PENDING".equals(t.state)||!t.expiresAt.isAfter(Instant.now())||!same(t.uploadTokenHash,token))throw new ImageUnavailableException();HeadObjectResponse h;try{h=s3.headObject(HeadObjectRequest.builder().bucket(bucket).key(t.objectKey).build());}catch(S3Exception e){throw new ImageUnavailableException();}if(h.contentLength()!=t.sizeBytes||!t.mimeType.equals(h.contentType()))throw new InvalidImageException();String code;do{code=value(6);}while(repo.findByPickupCode(code).isPresent()||text.pickupCodeExists(code));String del=value(43);t.ready(code,hash(del),Instant.now());return new Created(t.id,t.pickupCode,t.expiresAt,del);}
 @Transactional Retrieved get(String id){ImageTransfer t=repo.findById(id).orElseThrow(ImageUnavailableException::new);if(!t.live(Instant.now()))throw new ImageUnavailableException();String url=presigner.presignGetObject(GetObjectPresignRequest.builder().signatureDuration(Duration.ofSeconds(60)).getObjectRequest(GetObjectRequest.builder().bucket(bucket).key(t.objectKey).responseContentType(t.mimeType).build()).build()).url().toString();return new Retrieved(url,t.expiresAt,t.mimeType);}
 @Transactional String code(String raw){ImageTransfer t=repo.findByPickupCode(raw.trim().toUpperCase()).orElseThrow(ImageUnavailableException::new);if(!t.live(Instant.now()))throw new ImageUnavailableException();return t.id;}
 @Transactional void delete(String id,String token){ImageTransfer t=repo.findById(id).orElseThrow(ImageUnavailableException::new);if(!same(t.deleteTokenHash,token))throw new ImageUnavailableException();t.deleted(Instant.now());remove(t);}
 @Transactional @org.springframework.scheduling.annotation.Scheduled(fixedDelay=60000) public void cleanup(){for(ImageTransfer t:repo.findByExpiresAtLessThanEqual(Instant.now())){remove(t);repo.delete(t);}}
 void remove(ImageTransfer t){try{s3.deleteObject(DeleteObjectRequest.builder().bucket(bucket).key(t.objectKey).build());}catch(S3Exception ignored){}}
 String value(int n){char[] a=new char[n];for(int i=0;i<n;i++)a[i]=ALPH[random.nextInt(ALPH.length)];return new String(a);} String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}} boolean same(String h,String v){return h!=null&&v!=null&&MessageDigest.isEqual(h.getBytes(StandardCharsets.US_ASCII),hash(v).getBytes(StandardCharsets.US_ASCII));}
 record Init(String id,String uploadUrl,String uploadToken){} record Created(String id,String code,Instant expiresAt,String deleteToken){} record Retrieved(String imageUrl,Instant expiresAt,String mimeType){}
}
