<script setup lang="ts">
import { computed, nextTick, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ApiError, completeImageTransfer, createTextTransfer, initImageTransfer, resolveImagePickupCode, resolvePickupCode } from '../services/transfers'
const router=useRouter(),content=ref(''),image=ref<File|null>(null),preview=ref(''),creating=ref(false),sendError=ref(''),pickupError=ref(''),pickingUp=ref(false),codeDigits=ref(['','','','','','']),codeInputs=ref<HTMLInputElement[]>([]); const pickupCode=computed(()=>codeDigits.value.join(''))
function acceptImage(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){sendError.value='Only JPEG, PNG, and WebP images under 10 MB are supported.';return}image.value=file;content.value='';preview.value=URL.createObjectURL(file);sendError.value=''}
function chooseImage(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f)acceptImage(f)} function pasteImage(e:ClipboardEvent){const f=[...(e.clipboardData?.files??[])].find(x=>x.type.startsWith('image/'));if(f){e.preventDefault();acceptImage(f)}}
function onCodeInput(i:number,e:Event){codeDigits.value[i]=(e.target as HTMLInputElement).value.replace(/[^a-zA-Z0-9]/g,'').slice(-1).toUpperCase();if(codeDigits.value[i]&&i<5)nextTick(()=>codeInputs.value[i+1]?.focus())} function onCodeKeydown(i:number,e:KeyboardEvent){if(e.key==='Backspace'&&!codeDigits.value[i]&&i>0)nextTick(()=>codeInputs.value[i-1]?.focus())} function pasteCode(e:ClipboardEvent){e.preventDefault();const v=e.clipboardData?.getData('text').replace(/[^a-zA-Z0-9]/g,'').slice(0,6).toUpperCase()??'';codeDigits.value=Array.from({length:6},(_,i)=>v[i]??'');nextTick(()=>codeInputs.value[Math.min(v.length,5)]?.focus())}
async function createTransfer(){if(!image.value&&!content.value.trim()){sendError.value='Paste something first.';return}creating.value=true;sendError.value='';try{if(image.value){const init=await initImageTransfer(image.value.type,image.value.size);const upload=await fetch(init.uploadUrl,{method:'PUT',headers:{'Content-Type':image.value.type},body:image.value});if(!upload.ok)throw new Error();const t=await completeImageTransfer(init.id,init.uploadToken);sessionStorage.setItem(`pastehub:transfer:${t.id}`,JSON.stringify(t));sessionStorage.setItem(`pastehub:transfer-kind:${t.id}`,'image');await router.push(`/created/${t.id}`)}else{const t=await createTextTransfer(content.value);sessionStorage.setItem(`pastehub:transfer:${t.id}`,JSON.stringify(t));await router.push(`/created/${t.id}`)}}catch{sendError.value='Could not send. Try again.'}finally{creating.value=false}}
async function pickup(){if(pickupCode.value.length!==6)return;pickingUp.value=true;pickupError.value='';try{let t;try{t=await resolvePickupCode(pickupCode.value)}catch{t=await resolveImagePickupCode(pickupCode.value);sessionStorage.setItem(`pastehub:transfer-kind:${t.id}`,'image')}await router.push(`/t/${t.id}`)}catch(e){pickupError.value=e instanceof ApiError&&e.status===404?'Code is invalid or expired.':'Could not pick up. Try again.'}finally{pickingUp.value=false}}
</script>
<template><section class="minimal-demo" aria-labelledby="page-title"><h1 id="page-title">No login.<br><em>Just send it.</em></h1><form class="demo-composer" @submit.prevent="createTransfer" @paste="pasteImage"><textarea v-if="!image" v-model="content" maxlength="10000" placeholder="Paste text, or paste an image" aria-label="Content to send" :disabled="creating"/><div v-else class="demo-image-state"><img :src="preview" alt="Image to send"><strong>{{ image.name }}</strong><button type="button" @click="image=null;preview=''">Remove</button></div><div class="demo-composer-bar"><label>Image<input type="file" accept="image/jpeg,image/png,image/webp" hidden @change="chooseImage"></label><button type="submit" :disabled="creating">{{ creating?'Sending…':'Send' }} <span>↗</span></button></div></form><p v-if="sendError" class="form-error">{{ sendError }}</p><form class="demo-pickup" @submit.prevent="pickup"><label>Pick up with code</label><div class="demo-code-boxes" @paste="pasteCode"><input v-for="(_,i) in codeDigits" :key="i" :ref="el=>{if(el)codeInputs[i]=el as HTMLInputElement}" :value="codeDigits[i]" inputmode="text" maxlength="1" :aria-label="`Code digit ${i+1}`" @input="onCodeInput(i,$event)" @keydown="onCodeKeydown(i,$event)"></div><button :disabled="pickupCode.length!==6||pickingUp">{{ pickingUp?'Opening…':'Pick up' }}</button><p v-if="pickupError" class="form-error">{{ pickupError }}</p></form></section></template>
